# Generated by Django 3.1.3 on 2021-03-22 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_followup_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
